void telaGerenciarAlugueis(void);
void telaNovoAluguel(void);
void telaListarAlugueis(void);
void telaVerAluguel(char[]);
void telaEditarAluguel(char[]);
void telaExcluirAluguel(char[]);
void telaBuscarAluguel(void);
void telaRelatorioLucros(void);
void telaAlterarPreco(void);
